language: python

python:
  - "2.6"
  - "2.7"

install:
  - "pip install ."
  - "pip install --use-mirrors Django==1.4.2 python-memcached==1.48"

script:
  - "cd test_project/ && python manage.py test infinite_memcached"

services:
  - "memcache"

notifications:
  email: false
